### ISSUE TITLE
System.Threading.Tasks.Task Discord.IUserMessage.RemoveReactionAsync Method not found

### ISSUE THREAD

**Issue by EzzatBoukhary** [foxbot/Discord.Addons.Interactive#26]
Hello, Im using Discord.Addons.Interactive (latest version) and I recently updated to Discord.Net 2.2.0, it seems that the paged messages aren't working anymore. The bot adds the reactions but the ReactionAdded handler is throwing an unhandled exception when I react. Is there a way to fix this?
```
6:10 PM [Gateway] A ReactionAdded handler has thrown an unhandled exception.
Method not found: 'System.Threading.Tasks.Task Discord.IUserMessage.RemoveReactionAsync(Discord.IEmote, Discord.IUser, Discord.RequestOptions)'.
   at Discord.Addons.Interactive.PaginatedMessageCallback.HandleCallbackAsync(SocketReaction reaction)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Discord.Addons.Interactive.PaginatedMessageCallback.HandleCallbackAsync(SocketReaction reaction)
   at Discord.Addons.Interactive.InteractiveService.HandleReactionAsync(Cacheable`2 message, ISocketMessageChannel channel, SocketReaction reaction)
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
Method not found: 'System.Threading.Tasks.Task Discord.IUserMessage.RemoveReactionAsync(Discord.IEmote, Discord.IUser, Discord.RequestOptions)'.
```

**Comment by OoLunar** [comment]
Could we have a look at your code?

**Comment by TheStachelfisch** [comment]
Answered in #33
