### ISSUE TITLE
Method not found SendMessageAsync() in .net 5.0

### ISSUE THREAD

**Issue by NightKnight077** [foxbot/Discord.Addons.Interactive#35]
I am getting the below error when trying to send a paginated message to a channel using .net 5.0 and Discord.Net 2.4.0.

I am confused as I thought this was fixed in pull request #34 for issue #33 but I am still seeing the issue in my code. Is there something I am missing?

---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Discord.Rest.RestUserMessage> Discord.WebSocket.ISocketMessageChannel.SendMessageAsync(System.String, Boolean, Discord.Embed, Discord.RequestOptions)'.
         at Discord.Addons.Interactive.PaginatedMessageCallback.DisplayAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Discord.Addons.Interactive.PaginatedMessageCallback.DisplayAsync()
         at Discord.Addons.Interactive.InteractiveService.SendPaginatedMessageAsync(SocketCommandContext context, PaginatedMessage pager, ICriterion`1 criterion)

**Comment by pancine** [comment]
While it doesn't support Discord.NET +2.4.0, try to downgrade all Discord.NET packages to 2.2.0

**Comment by kollibroman** [comment]
Use one of the forks, they have updated versions of packages
